### ISSUE TITLE
"8.4 mode" toggle in the wrong place

### ISSUE THREAD

**Issue by Darthagnon** [PoomSmart/EmojiLayout#2]
As I mentioned [here](https://github.com/PoomSmart/EmojiPort-Legacy/issues/16), EmojiLayout puts a switch in the wrong place in the Settings app - instead of being in the EmojiLayout submenu, the "8.4 mode" switch is mixed into the tweak settings masterlist. This occurs on iOS 7.1.2 (I didn't have to install EmojiLayout as a dependency on other iOS versions.

**Comment by PoomSmart** [comment]
iOS 8.3+ UI is EmojiPort-specific feature. It has nothing to do with the number of rows and columns of the emojis grid. Rather, it adds a category name, removes page dots and alters some colors as can be seen in this file: https://github.com/PoomSmart/EmojiPort-Legacy/blob/master/iOS83UI.xm
